server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

